### ISSUE TITLE
Add Instagram, Soundcloud, Youtube embeds in the whitelist.

### ISSUE THREAD

**Issue by Rtizer-9** [Cimbali/CleanLinks#85]
I would like to report some urls where Cleanlinks breaks the functionality.

1. https://www.newslaundry.com/2020/03/17/nl-interview-journalist-govindraj-ethiraj-on-busting-fake-news-and-data-literacy

Whitelisting soundcloud resolves the issue.

2. https://graziadaily.co.uk/life/real-life/politics-birthday-posts-social-media/
3. https://news.artnet.com/art-world/instagram-fake-news-filter-1761660

Whitelisting instagram here resolves the issue.

4. https://www.medianama.com/

Youtube embed has been completely blocked here (I'm talking about the video in the right side)

Thus I think there can be a better rule for these domains on the whitelist.

Btw, I was so happy after receiving the update after such a long time and what an update man. It's great that the project is alive. Really great work!!!

**Comment by Cimbali** [comment]
Thanks for reporting, and thanks a lot for the support ! :heart:  I’ve been wanting to get back to CleanLinks for a while, and I must say the v3 has been received with a lot more… defiance than I expected.

For youtube embeds, those should already be solved. You probably need to go to the CleanLinks Options page and click “Reset Rules”. I’ll have a look at the other whitelists you suggest !

**Comment by Rtizer-9** [comment]
I've used reset rules/options earlier for other purposes and just now again after your suggestion but that particular medianama.com page has the same YouTube embed blocking error. 

Please check on your side that you can replicate the scenario or not.

**Comment by Cimbali** [comment]
Good catch! The following rule works for me, will add it into the rules with the next release:

- domain `www.youtube.com`
- path `^/embed/`
- remove query parameters `origin`

**Comment by Rtizer-9** [comment]
Great. Well, the SoundCloud rule can be added simply by the whitelist menu as it is because of it's simple and same format across every domain but the instagram one requires a more complex one as the uid is different on every domain. You must have found out that by now most probably.

Btw, your addon needs to be their at ghacks project along with neat url and clearurls.

I do remember someone (maybe you yourself) tried to do it earlier but it's still not recommended on their extension page.

I'm not saying every privacy project needs a certification from ghacks but having your addon listed their is a great way to get more users because of it's popularity.

**Comment by Rtizer-9** [comment]
The latest commit does solve the youtube and soundcloud issue but the instagram issue is still not resolved. Can you please check?

**Comment by Cimbali** [comment]
Don’t know what happened there. The rule was indeed missing from the update. Pushing a new one right now.

**Comment by Rtizer-9** [comment]
I think this url https://graziadaily.co.uk/life/real-life/politics-birthday-posts-social-media/ needs a different rule. The commit doesn't work in this case.

https://news.artnet.com/art-world/instagram-fake-news-filter-1761660
works perfectly now.

**Comment by Rtizer-9** [comment]
I got another page where current instagram rule breaks the functionality:

https://www.hindustantimes.com/tv/she-review-imtiaz-ali-s-bad-luck-spills-onto-sleazy-sloppy-new-netflix-series/story-21xW4GUI1k5Z4j7yZTEcVI.html 

Here the we have "tv" in the place of "p" in rule:
^/p/\w+/embed/captioned/$

I modified this rule by replacing p by \w+

so now the rule is:

^/\w+/\w+/embed/captioned/$

Now the page works fine.

Although I think this rule will suffice in these kinda cases, I don't have regex knowlegde so please make appropriate changes in the next version.

**Comment by Rtizer-9** [comment]
Some youtube embed here need some working.

[https://www.theverge.com/2017/4/5/15194374/youtube-tv-live-streaming-10-important-things-to-know](url)

**Comment by Cimbali** [comment]
Thanks @Rtizer-9 !

By the way, this is nothing important but I keep editing your posts because your links all point to `url`. I think you click the “insert URL” button, insert the link in the text part of the link and leave `url` in the url part.

You can either:
- simply paste the URL as-is.
- paste the URL between angle brackets, which is useful if the automatic detection of the URL does something wrong `<url-here>`
- use the URl with text format `[text-here](url-here)`

**Comment by Rtizer-9** [comment]
I actually had a github modifying addon installed for so long that the real GitHub interface is something new for me.

I'll keep the suggestions in mind next time.

**Comment by Cimbali** [comment]
To solve this youtube issue, you can seach for the youtube embed rule (eg. `youtube/embed` in the filter) and add `widget_referrer` to the parameter removal.

I’ve added it to the default rules (as `.*referrer`) so it catches any other similar parameters or just `referrer` as well.

**Comment by Rtizer-9** [comment]
Yeah the whitelist option already added that parameter.
